/**
 * Editable draft state for one catalogue.
 *
 * Every field an author types is kept as a plain string (even numbers and
 * units), so a half-typed value never has to be coerced or rejected while
 * the author is still typing — `validation.ts` is the only place drafts get
 * interpreted, all at once, against the real `@joveworks/schema` parser.
 * `key` fields exist only for React identity/list operations and are never
 * part of the exported JSON.
 */

import {
  appliesWhenOf,
  soleExpression,
  serializeFormula,
  type Formula,
  type FormulaStatus,
  type Catalogue,
  type JsonValue,
  type LocalizedText,
  type Monotonicity,
  type Port,
} from '@joveworks/schema';

export type DraftLocalizedText = Readonly<Record<string, string>>;

export type DraftPortKind = 'numeric' | 'categorical';

export interface DraftValidRange {
  readonly min: string;
  readonly max: string;
}

export interface DraftPort {
  readonly key: string;
  readonly kind: DraftPortKind;
  readonly name: string;
  /** Numeric only. */
  readonly unit: string;
  readonly preferredUnit: string;
  /** Numeric default, or the categorical default value. */
  readonly defaultValue: string;
  readonly validRange: DraftValidRange;
  readonly monotonic: Monotonicity | '';
  /** Categorical only, comma-separated. */
  readonly domain: string;
  /** Numeric only: this input takes several wires instead of one. */
  readonly variadic: boolean;
  readonly description: DraftLocalizedText;
}

export interface DraftFormula {
  readonly key: string;
  readonly id: string;
  readonly version: string;
  readonly outputs: readonly DraftPort[];
  readonly inputs: readonly DraftPort[];
  readonly expression: string;
  readonly label: DraftLocalizedText;
  readonly description: DraftLocalizedText;
  readonly citation: string;
  readonly variantOf: string;
  readonly appliesWhen: string;
  readonly status: FormulaStatus;
  readonly quarantineReason: DraftLocalizedText;
  /**
   * A lookup table round-trips untouched — there is no editor for the dense
   * axis/value arrays `FormulaLookup` holds, since these are normally
   * machine-generated by `tools/extract`, not hand-authored. Carried as
   * already-serialized JSON captured at import time.
   */
  readonly lookupJson?: JsonValue;
  /**
   * The same treatment for a record answering with several outputs: the one
   * `expression` field above edits a single relation, so a per-output map
   * round-trips as captured JSON rather than being flattened to whichever
   * expression happened to come first. Set only when there is more than one.
   */
  readonly expressionJson?: JsonValue;
}

export interface DraftCatalogue {
  readonly id: string;
  readonly name: DraftLocalizedText;
  readonly restricted: boolean;
  readonly formulas: readonly DraftFormula[];
}

let keyCounter = 0;
function nextKey(prefix: string): string {
  keyCounter += 1;
  return `${prefix}-${keyCounter}`;
}

export function emptyPort(kind: DraftPortKind): DraftPort {
  return {
    key: nextKey('port'),
    kind,
    name: '',
    unit: '',
    preferredUnit: '',
    defaultValue: '',
    validRange: { min: '', max: '' },
    monotonic: '',
    domain: '',
    variadic: false,
    description: {},
  };
}

export function emptyFormula(): DraftFormula {
  return {
    key: nextKey('formula'),
    id: '',
    version: '1',
    outputs: [emptyPort('numeric')],
    inputs: [],
    expression: '',
    label: {},
    description: {},
    citation: '',
    variantOf: '',
    appliesWhen: '',
    status: 'unverified',
    quarantineReason: {},
  };
}

export function emptyCatalogue(): DraftCatalogue {
  return { id: '', name: {}, restricted: false, formulas: [] };
}

function draftLocalizedTextFromReal(text: LocalizedText | undefined): DraftLocalizedText {
  return text === undefined ? {} : { ...text };
}

function draftPortFromReal(port: Port): DraftPort {
  const base = {
    key: nextKey('port'),
    name: port.name,
    description: draftLocalizedTextFromReal(port.description),
  };
  switch (port.kind) {
    case 'categorical':
      return {
        ...base,
        kind: 'categorical',
        unit: '',
        preferredUnit: '',
        defaultValue: port.default ?? '',
        validRange: { min: '', max: '' },
        monotonic: '',
        domain: port.domain.join(', '),
        variadic: false,
      };
    case 'bundle':
      // No catalogue formula declares one (see packages/schema/src/port.ts's
      // own doc comment) — represented as an empty numeric stub rather than
      // modelled properly, since this app never produces or expects one.
      return {
        ...base,
        kind: 'numeric',
        unit: '',
        preferredUnit: '',
        defaultValue: '',
        validRange: { min: '', max: '' },
        monotonic: '',
        domain: '',
        variadic: false,
      };
    case 'numeric':
    default:
      return {
        ...base,
        kind: 'numeric',
        unit: port.unit.symbol,
        preferredUnit: port.preferredUnit?.symbol ?? '',
        defaultValue: port.default === undefined ? '' : String(port.default),
        validRange: {
          min: port.validRange?.min === undefined ? '' : String(port.validRange.min),
          max: port.validRange?.max === undefined ? '' : String(port.validRange.max),
        },
        monotonic: port.monotonic ?? '',
        domain: '',
        variadic: port.variadic ?? false,
      };
  }
}

/** The one condition a single-output record states, matching `soleExpression`. */
function soleAppliesWhen(formula: Formula): string | undefined {
  const only = formula.outputs[0];
  return formula.outputs.length === 1 && only !== undefined
    ? appliesWhenOf(formula, only.name)
    : undefined;
}

export function draftFormulaFromReal(formula: Formula): DraftFormula {
  return {
    key: nextKey('formula'),
    id: formula.id,
    version: String(formula.version),
    outputs: formula.outputs.map(draftPortFromReal),
    inputs: formula.inputs.map(draftPortFromReal),
    expression: soleExpression(formula) ?? '',
    label: draftLocalizedTextFromReal(formula.label),
    description: draftLocalizedTextFromReal(formula.description),
    citation: formula.citation ?? '',
    variantOf: formula.variantOf ?? '',
    appliesWhen: soleAppliesWhen(formula) ?? '',
    status: formula.status,
    quarantineReason: draftLocalizedTextFromReal(formula.quarantineReason),
    ...(formula.lookup === undefined ? {} : { lookupJson: serializeFormula(formula).lookup }),
    ...(formula.outputs.length === 1 ? {} : { expressionJson: serializeFormula(formula).expression }),
  };
}

export function draftCatalogueFromReal(catalogue: Catalogue): DraftCatalogue {
  return {
    id: catalogue.id,
    name: draftLocalizedTextFromReal(catalogue.name),
    restricted: catalogue.restricted,
    formulas: catalogue.formulas.map(draftFormulaFromReal),
  };
}

// --- Catalogue-level list operations -------------------------------------

export function addFormula(catalogue: DraftCatalogue): DraftCatalogue {
  return { ...catalogue, formulas: [...catalogue.formulas, emptyFormula()] };
}

export function duplicateFormula(catalogue: DraftCatalogue, key: string): DraftCatalogue {
  const index = catalogue.formulas.findIndex((formula) => formula.key === key);
  if (index === -1) return catalogue;
  const source = catalogue.formulas[index]!;
  const copy: DraftFormula = {
    ...source,
    key: nextKey('formula'),
    id: source.id === '' ? '' : `${source.id}-copy`,
    outputs: source.outputs.map((port) => ({ ...port, key: nextKey('port') })),
    inputs: source.inputs.map((port) => ({ ...port, key: nextKey('port') })),
  };
  const formulas = [...catalogue.formulas];
  formulas.splice(index + 1, 0, copy);
  return { ...catalogue, formulas };
}

export function removeFormula(catalogue: DraftCatalogue, key: string): DraftCatalogue {
  return { ...catalogue, formulas: catalogue.formulas.filter((formula) => formula.key !== key) };
}

export function moveFormula(catalogue: DraftCatalogue, key: string, direction: -1 | 1): DraftCatalogue {
  const index = catalogue.formulas.findIndex((formula) => formula.key === key);
  const target = index + direction;
  if (index === -1 || target < 0 || target >= catalogue.formulas.length) return catalogue;
  const formulas = [...catalogue.formulas];
  const [item] = formulas.splice(index, 1);
  formulas.splice(target, 0, item!);
  return { ...catalogue, formulas };
}

export function updateFormula(
  catalogue: DraftCatalogue,
  key: string,
  patch: Partial<DraftFormula>,
): DraftCatalogue {
  return {
    ...catalogue,
    formulas: catalogue.formulas.map((formula) => (formula.key === key ? { ...formula, ...patch } : formula)),
  };
}

// --- Formula-level port operations ----------------------------------------

export function addPort(formula: DraftFormula, kind: DraftPortKind): DraftFormula {
  return { ...formula, inputs: [...formula.inputs, emptyPort(kind)] };
}

export function removePort(formula: DraftFormula, key: string): DraftFormula {
  return { ...formula, inputs: formula.inputs.filter((port) => port.key !== key) };
}

export function movePort(formula: DraftFormula, key: string, direction: -1 | 1): DraftFormula {
  const index = formula.inputs.findIndex((port) => port.key === key);
  const target = index + direction;
  if (index === -1 || target < 0 || target >= formula.inputs.length) return formula;
  const inputs = [...formula.inputs];
  const [item] = inputs.splice(index, 1);
  inputs.splice(target, 0, item!);
  return { ...formula, inputs };
}

/** Updates an output port when `key` matches one, otherwise an input port. */
export function updatePort(formula: DraftFormula, key: string, patch: Partial<DraftPort>): DraftFormula {
  if (formula.outputs.some((port) => port.key === key)) {
    return {
      ...formula,
      outputs: formula.outputs.map((port) => (port.key === key ? { ...port, ...patch } : port)),
    };
  }
  return {
    ...formula,
    inputs: formula.inputs.map((port) => (port.key === key ? { ...port, ...patch } : port)),
  };
}
